version: "3.7"
services:
  smart-analytics-service:
    container_name: smart-analytics
    restart: on-failure
    build: .
    depends_on:
      - postgresql-database
    ports:
      - "8080:8080"
  postgresql-database:
    image: 'postgres:13.1-alpine'
    container_name: postgresql
    environment:
      - POSTGRES_USER=smart-analytics-app
      - POSTGRES_PASSWORD=PQMqe87hupwsZiASMJ3R
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_DB=smart-analytics
    ports:
      - "5432:5432"
