server:
  port: 8080

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  main:
    web-application-type: reactive
  r2dbc:
    username: smart-analytics-app
    password: PQMqe87hupwsZiASMJ3R
    url: r2dbc:postgresql://localhost:5432/
    name: smart-analytics
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    data:
      r2dbc:
        username: smart-analytics-app
        repositories:
          enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
  security:
    enabled: true

token:
  jwt-secret: 3cd31293-9b20-487e-bd88-858f4e330067

