server:
  port: 8080

spring:
  main:
    web-application-type: reactive
  r2dbc:
    username: ${postgresql.username}
    password: ${postgresql.password}
    url: ${postgresql.url}
    name: smart-analytics
    pool:
      enabled: true
      initial-size: 10
      max-idle-time: 1m
      max-size: 30
    data:
      r2dbc:
        username: ${postgresql.username}
        repositories:
          enabled: true
  jpa:
    generate-ddl: true
    show-sql: true
  security:
    enabled: true

token:
  jwt-secret: ${token.jwt-secret}

